# Generated by Django 4.2 on 2023-04-23 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_remove_post_hashtags_delete_hashtag_post_hashtags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="author",
            new_name="user",
        ),
    ]
