# Generated by Django 4.2 on 2023-04-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0002_rename_profile_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
