# Generated by Django 4.2 on 2023-04-23 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_followers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["is_staff", "id"]},
        ),
    ]
