# Generated by Django 4.2 on 2023-04-23 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("follower", "0003_alter_follower_followee"),
        ("user", "0003_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                related_name="followers_of",
                through="follower.Follower",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
