# Generated by Django 4.2 on 2023-04-23 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_user_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="following",
        ),
    ]
