# Generated by Django 4.2 on 2023-04-23 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_remove_user_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="followers",
        ),
    ]
