# Generated by Django 4.2 on 2023-04-23 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("follower", "0004_alter_follower_followee_alter_follower_user"),
        ("user", "0006_remove_user_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                related_name="user_followers",
                through="follower.Follower",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
